moodle:
  image:
    registry: docker.io
    repository: yzhou442/equiz
    tag: latest
    digest: ""
    pullPolicy: Always
    pullSecrets: []
    debug: false
    websiteUrl: deep.cs.cityu.edu.hk/equiz
    reverseProxy: '"true"'
    sslProxy: '"true"'
  
  moodleEmail: equiz@cs.cityu.edu.hk
  moodleUsername: admin-custom
  moodlePassword: admin123
  
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    hostname: deep.cs.cityu.edu.hk
    path: /equiz
    pathType: Prefix
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: 200M
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    tls: true
    ingressClassName: public

jobe:
  jobeImage: docker.io/yzhou442/jobeinabox
