apiVersion: v1
kind: Service
metadata:
  labels:
    service: jobe
  name: jobe
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    service: jobe
status:
  loadBalancer: {}
